### ISSUE TITLE
Condition question

### ISSUE THREAD

**Issue by ms32035** [5had3z/stereo-to-all#2]
Hi

I'm trying to apply your ScatterND plugin to some other generic network, and I'm hitting issues with format conditions here:

- https://github.com/5had3z/stereo-to-all/blob/master/runtime/cerberus_net/trt_plugins/scatter_nd.cpp#L91
- https://github.com/5had3z/stereo-to-all/blob/master/runtime/cerberus_net/trt_plugins/scatter_nd.cpp#L69
- https://github.com/5had3z/stereo-to-all/blob/master/runtime/cerberus_net/trt_plugins/scatter_nd.cpp#L109

Are these conditions a hard requirements of ScatterND or specific to the network you're using?

**Comment by 5had3z** [comment]
For my application, all tensors are {batch, channel, height, width} (which are the formats of the input, update and output), the indicies dimensions are {batch, channel, height, width, target co-ords} where target co-ords is equal to the number dimensions of the inputs/outputs, which would be 4 in this case. ScatterND for ONNX is Input, Indicies, Updates and Output so there should be three inputs and one output. The conditions at 69, 96 and 109 cover all of these conditions and this implementation works for me in both FP32 and FP16 modes.

When removing inOut[pos].format == nvinfer1::TensorFormat::kLINEAR, TRT warns that more than 100 combinations are available and therefore some are skipped. The other formats add flavours of vectorisation across channels so you can use half2 ops or the DLA engine (this adds another dimension, for example nvinfer1::TensorFormat::kCHW2 -> {N,C/2,H,W,2}). This is probably why you're having an issue with both the 91 and 109, as you have this additional channel, but I would think you should also have an issue with 96. Another kernel would have to be written for these vectorised formats as we now have a new addressing system as the channel strides are spread across the second and last dimensions.

The kernel is designed with these conditions in mind, so I have doubts it'll work when removing these. I also haven't properly batched this yet either as I only work with batchsize 1, however it would be simple to just use an additional dimension to the thread block to achieve this (maybe I'll update later).

**Comment by ms32035** [comment]
Thanks for the answer. You're right, my typo. it was line 96 not 69 that was giving me troubles too.
