### ISSUE TITLE
Boundary check for trt_plugins/ScatterND

### ISSUE THREAD

**Issue by buganini** [5had3z/stereo-to-all#4]
FYI, not sure if this is the best method, I am new to CUDA.
```
-            output[out_n_stride*output_n + out_c_stride*output_c + out_h_stride*output_h + output_w] =
-                updates[ch * out_c_stride + tid];
+            if(
+                (0 <= output_c && output_c < out_channels)
+                &&
+                (0 <= output_h && output_h < out_height)
+                &&
+                (0 <= output_w && output_w < out_width)
+            ){
+                output[out_n_stride*output_n + out_c_stride*output_c + out_h_stride*output_h + output_w] =
+                    updates[ch * out_c_stride + tid];
+            }
```

OnnxRuntime uses clamping approach https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/tensor/scatter_nd_impl.cu#L33

**Comment by 5had3z** [comment]
The indicies that are being sourced from should all be valid, or at least that has been the case for me so far. Are you having issues with illegal memory accesses?

This is the resource I used to get into CUDA programming almost a year ago, if you were interested: https://classroom.udacity.com/courses/cs344/

**Comment by buganini** [comment]
Yes, I get memory access issue with an onnx converted from pytorch model.

**Comment by 5had3z** [comment]
I've just got my replacement PSU in and have tested master branch which works fine. Here's a link to an onnx graph that works fine for me. What version of tensorrt and onnx are you using?

https://drive.google.com/file/d/1rN90pkVZcFqOQ0vxtRswB0R2U1m9dV69/view?usp=sharing

**Comment by buganini** [comment]
https://github.com/HKBU-HPML/FADNet/blob/master/networks/submodules.py#L94

This function is turned into a huge network when it is converted to ONNX, this is where I get the issue.

**Comment by buganini** [comment]
I am using
tensorrt 7.1.3.0-1+cuda10.2 arm64
on my laptop and
tensorrt 7.2.2.3-1+cuda11.1 amd64
on Jetson Xavier NX
